name: Generate Documentation (on Qt5.6)

on:
  release:
    types: [published]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow only one build run, skipping runs queued between the run in-progress and latest queued.
# cancel in-progress runs
concurrency:
  group: "gendoc"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      SEGMENT_DOWNLOAD_TIMEOUT_MINS: 3
      # branch to compile from, and branch to commit/push to
      DOC_SOURCE_BRANCH: "master"
      DOC_TARGET_BRANCH: "gh-pages"
      # Output location for generated content so we know where to copy from.
      # Not related to output path in the repo.
      DOC_TARGET_DIR:    "doctarget"
    steps:
    - name: Checkout Source (${{ env.DOC_SOURCE_BRANCH }})
      uses: actions/checkout@v3
      with:
        ref: ${{ env.DOC_SOURCE_BRANCH }}

    - name: Generate Docs
      env:
        # docker image to run qdoc etc. on
        DOCKER_IMG:        "icsinc/qt5.6.1-x64:latest"
      run: |
        docker run --rm -v $PWD:/share $DOCKER_IMG /bin/bash -xc "
            echo 'debconf debconf/frontend select Noninteractive' | sudo debconf-set-selections;
            sudo rm -f /etc/apt/sources.list.d/beineri-opt-qt561-trusty-trusty.list
            sudo apt-get -qq update;
            sudo apt-get -qq install -y qtbase5-dev;
            sudo apt-get -qq install -y git-core;
            mkdir -p build ;
            cd build ;
            cp -r /share/* . ;
            mkdir -p doc/generated;
            git clone --depth 1 -b upgrade-4.5.0 https://github.com/sailfishos/sailfish-qdoc-template doc/qdoc/sailfish-qdoc-template;
            /bin/bash -c ./makedocs;
            mkdir /share/out;
            cp -rv doc/generated/* /share/out/;
            "

    # Now deploy to GH Pages
    - name: Setup Pages
      uses: actions/configure-pages@v3
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: './out'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
      permissions:
        contents: write
